apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: counter
  name: counter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter
  template: 
    metadata:
      labels:
        app: counter
    spec:
      containers:
        - image: maheshkasbe/counter-app:latest
          name: counter-container
          ports:
            - containerPort: 3000